In the next notebook that:
    - clean the data contained in the CSV
    - set threshold for flow to be included in models
    - build models (using Lasso Regression, we believe)
    - set threshold for accuracy in predicting flow
    - throw out models that do not meet that accuracy
    - throw out features in models that are no longer needed
    - do other prep for putting models into production (test in real time and have accuracy feedback)

In [15]:
import pandas as pd
import os

In [16]:
import pickle
path="C:\Springboard\Github\gauge_info"
os.chdir(path)

In [17]:
# load the dataframe of targets and their corresponding features
dt = pickle.load(open("USGS_targets.pkl", "rb"))
dt

USGS        lat        long      alt                basin  \
0           10140700  41.231819  111.984497  4285.00          Lower Weber   
1           10149000  40.118012  111.314622  6320.00         Spanish Fork   
2           10155200  40.554398  111.433243  5691.59                Provo   
79          09064600  39.553875  106.402529  8078.37                Eagle   
84          09081000  39.373317  107.083937  6470.00         Roaring Fork   
85          09073300  39.141100  106.774204  8120.00         Roaring Fork   
86          09075400  39.193833  106.833667  7882.00         Roaring Fork   
87          09033300  40.006892  105.848272  8274.00  Colorado Headwaters   
88          09359010  37.802774  107.672839  9245.98               Animas   
92          09358000  37.811108  107.659228  9290.00               Animas   
93          09359020  37.788333  107.668222  9199.00               Animas   
94          09359500  37.597417  107.776967  7682.00               Animas   
99          09146020  38.043327  107.683115  7600.00          Uncompahgre   
100         09112200  38.784160  106.870874  8440.00          East-Taylor   
102         09037500  40.000200  106.180367  7808.95  Colorado Headwaters   
108         09413500  37.014424  113.680516  2401.58         Lower Virgin   
113         09060799  39.891100  106.831694  6544.00  Colorado Headwaters   
121         09421500  36.015258  114.738594   675.49  Havasu-Mohave Lakes   
122  385106106571000  38.851659  106.953377  8810.00          East-Taylor   
151         09076300  39.223200  106.857308  7575.00         Roaring Fork   

            lng                                          feat_USGS  \
0   -111.984497  [10126000, 10092700, 10010000, 10171000, 10105...   
1   -111.314622  [10164500, 10133800, 10133650, 10133600, 09313...   
2   -111.433243  [10164500, 10131000, 10134500, 10132500, 10155...   
79  -106.402529  [09057500, 09034250, 09034500, 09065100, 09063...   
84  -107.083937  [09132095, 09070500, 09085100, 09081600, 09070...   
85  -106.774204  [09065100, 09112500, 09078600, 09080400, 09066...   
86  -106.833667  [09065100, 09112500, 09078600, 09080400, 09066...   
87  -105.848272  [09050700, 09010500, 09034250, 09019500, 09034...   
88  -107.672839  [09126000, 09118450, 09165000, 09074000, 09365...   
92  -107.659228  [09126000, 09118450, 09165000, 09074000, 09365...   
93  -107.668222  [09126000, 09118450, 09165000, 09074000, 09365...   
94  -107.776967  [09147000, 09166500, 09165000, 09365500, 09124...   
99  -107.683115  [09147000, 09114500, 09365500, 09124500, 09370...   
100 -106.870874  [09118450, 09112500, 09078600, 09114500, 09074...   
102 -106.180367  [09057500, 09034250, 09019500, 09034500, 09065...   
108 -113.680516  [09414900, 09408195, 09418700, 09413000, 09408...   
113 -106.831694  [09070500, 09081600, 09070000, 09242500, 09246...   
121 -114.738594  [09423000, 09419696, 09419753, 09419700, 09419...   
122 -106.953377  [09126000, 09118450, 09078600, 09064000, 09074...   
151 -106.857308  [09067020, 09112500, 09078600, 09080400, 09114...   

                                             feat_NOAA  
0    [BCNU1, BIUI1, GSPU1, JRSU1, PRZU1, LCJU1, LGN...  
1    [AFPU1, ECAU1, ECPU1, MCLU1, PRHU1, PVHU1, SCJ...  
2    [AFPU1, CIVU1, ECCU1, CRDU1, PVHU1, RBCU1, CLL...  
79   [BGMC2, CAWC2, HTSC2, CSSC2, RERC2, FRGC2, FPT...  
84   [ACSC2, EGLC2, GCOC2, RCYC2, GPSC2, ENMC2, GEP...  
85   [CSSC2, ALEC2, FPTC2, RUDC2, GRVC2, GUSC2, HUN...  
86   [CSSC2, ALEC2, FPTC2, RUDC2, GRVC2, GUSC2, OHO...  
87   [BLRC2, BAKC2, CAWC2, CBGC2, HTSC2, FRGC2, FRW...  
88   [CMRC2, CRCC2, DRRC2, HUNC2, LPHC2, LFBC2, LFG...  
92   [CMRC2, CRCC2, DRRC2, HUNC2, LPHC2, LFBC2, LFG...  
93   [CMRC2, CRCC2, DRRC2, HUNC2, LPHC2, LFBC2, LFG...  
94   [DCKC2, DOLC2, DRRC2, LPHC2, LFGC2, LCCC2, MNR...  
99   [DCKC2, GUSC2, LPHC2, LFGC2, MNRC2, OHOC2, SMP...  
100  [CRCC2, ALEC2, FPTC2, GUSC2, HUNC2, OHOC2, APN...  
102  [BGMC2, CAWC2, CBGC2, HTSC2, CSSC2, FRGC2, GRV...  
108  [BEAA3, FP

How do I want to structure this? <br>
 - loop through the rows of the data structure
 - pull in the data from the corresponding CSV files
 - parse CSV so that that flow from target (y) is first column; flow from additional features is in other columns (x's)
 - save model (what is the best data structure for saving multiple models?)

In [18]:
# first, how do I parse these CSV files appropriately?!?!


In [19]:
# read the raw CSV back in and remove the commented lines
raw_file = '09010500.csv'
# open raw CSV
fi = open(raw_file, 'r')

# read raw CSV to clean CSV - eliminate comment rows with "#"
clean_file = 'clean_' + raw_file
with open(clean_file, 'w') as fo:
    lines = fi.readlines()
    for line in lines:
        if "#" not in line:
            fo.write(line)
fi.close()

In [20]:
# let's see if that loads as a dataframe now
df = pd.read_csv(clean_file, error_bad_lines=False, delimiter='\t')
df

agency_cd   site_no    datetime 18363_00060_00003 18363_00060_00003_cd
0            5s       15s         20d               14n                  10s
1          USGS  09010500  1953-06-01               279                    A
2          USGS  09010500  1953-06-02               286                    A
3          USGS  09010500  1953-06-03               293                    A
4          USGS  09010500  1953-06-04               279                    A
...         ...       ...         ...               ...                  ...
24831      USGS  09010500  2021-05-25               226                    P
24832      USGS  09010500  2021-05-26               226                    P
24833      USGS  09010500  2021-05-27               236                    P
24834      USGS  09010500  2021-05-28               248                    P
24835      USGS  09010500  2021-05-29               242                    P

[24836 rows x 5 columns]

I think this looks great! We just need to drop the first row, the first column, the second column, and the last column.

In [21]:
# drop the first row
df.drop([0], inplace=True)

In [22]:
# drop the first and second columns
df.drop(columns=['agency_cd', 'site_no'], inplace=True)
df

datetime 18363_00060_00003 18363_00060_00003_cd
1      1953-06-01               279                    A
2      1953-06-02               286                    A
3      1953-06-03               293                    A
4      1953-06-04               279                    A
5      1953-06-05               264                    A
...           ...               ...                  ...
24831  2021-05-25               226                    P
24832  2021-05-26               226                    P
24833  2021-05-27               236                    P
24834  2021-05-28               248                    P
24835  2021-05-29               242                    P

[24835 rows x 3 columns]

In [23]:
last_name = list(df.columns)
last_name[-1:][0]

'18363_00060_00003_cd'

In [24]:
df = df.iloc[:, :-1]
df

datetime 18363_00060_00003
1      1953-06-01               279
2      1953-06-02               286
3      1953-06-03               293
4      1953-06-04               279
5      1953-06-05               264
...           ...               ...
24831  2021-05-25               226
24832  2021-05-26               226
24833  2021-05-27               236
24834  2021-05-28               248
24835  2021-05-29               242

[24835 rows x 2 columns]

In [25]:
df.columns[1]

'18363_00060_00003'

In [26]:
to_rename = df.columns[1]
df.rename(columns={to_rename: 'flow'})

datetime flow
1      1953-06-01  279
2      1953-06-02  286
3      1953-06-03  293
4      1953-06-04  279
5      1953-06-05  264
...           ...  ...
24831  2021-05-25  226
24832  2021-05-26  226
24833  2021-05-27  236
24834  2021-05-28  248
24835  2021-05-29  242

[24835 rows x 2 columns]

That completes pulling in the data that we would need and cleaning it - for just one gage. Let's write that into a function so the result is a df that just contains datetime and cfs.

In [95]:
def load_csv(USGS):
    # read the raw CSV back in and remove the commented lines
    raw_file = USGS + '.csv'
    # open raw CSV
    try:
        fi = open(raw_file, 'r')
    except:
        return pd.DataFrame()

    # read raw CSV to clean CSV - eliminate comment rows with "#"
    clean_file = 'clean_' + raw_file
    with open(clean_file, 'w') as fo:
        lines = fi.readlines()
        for line in lines:
            if "#" not in line:
                fo.write(line)
    fi.close()
    # reloads that clean file
    df = pd.read_csv(clean_file, error_bad_lines=False, delimiter='\t')
    # drop the first row
    df.drop([0], inplace=True)
    # drop some other irrelevant columns
    df.drop(columns=['agency_cd', 'site_no'], inplace=True)
    # drop the last column
    df = df.iloc[:, :-1]
    # rename the remaining last column to the name of the USGS gage - better when appended
    to_rename = df.columns[1]
    df.rename(columns={to_rename: USGS}, inplace=True)
    
    # see if we can rename the column by number - use USGS as the name of the second column!!!!
    
    ##### consider replacing strings with other values here
    df.replace(to_replace=['Ice', 'Ssn', 'Bkw', 'A'], value=[0, 0, 0, 0], inplace=True)
    # 'ice' = 0
    
    
    return df

Let's start to write the loop for the pulling that all into one dataframe

In [71]:
from sklearn import linear_model
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedKFold
from sklearn.linear_model import Lasso
import numpy as np
from sklearn.model_selection import cross_val_score

In [96]:

# this loop pulls the CSV data into a dataframe
for i, row in dt.iterrows():
    # loads the data of the target
    df = load_csv(row['USGS'])
    gages = row['feat_USGS']
    # loop to load the data of the features
    for g in gages:
        # load the data of each feature
        df1 = load_csv(g)
        # merge the dataframes - match on date
        try:
            df = pd.merge(df, df1, how='left', on='datetime')
        except:
            pass
    # drop rows that contain NaN in the second column (target)
    name = df.columns[1]
    df.dropna(subset=[name], inplace=True)
    
    # creates backup in case we drop too many columns
    dfb = df.copy()
    print(name)
    print(dfb.shape)
    
    # drop any columns that contain Nan
    df.dropna(axis=1, inplace=True)
    
    # check to make sure there are no NaN values and nothing is infinite
#     print(df.isna().any())
#     print(np.isnan(df.any()))
#     print(np.isfinite(df.all()))
    
    
    # split into X and Y
    X, y = df.iloc[:, 2:], df.iloc[:, 1]
    # using the LassoCV to build the model
    if X.shape[1] > 0:
        A = [.5, 1, 2.5, 5, 7.5, 10, 15, 20, 25, 30, 35, 40, 50, 100, 200, 250, 300, 350, 400, 450, 500, 750, 1000, 10000]
        reg = linear_model.LassoCV(cv=5, random_state=33, alphas=A).fit(X, y)
        score = reg.score(X,y)
        print(score)
        print(reg.coef_)
        print(reg.intercept_)
        print(reg.alpha_)
    else:
        score = 0
    # if there are no features left after dropping the Nan columns, we try again OR if 
    if score < 0.75:
        df = dfb.copy()
        # drop any rows that contain Nan (we need more features!)
        df.dropna(axis=1, how='all', inplace=True)
        df.dropna(axis=0, inplace=True)
        # split into X and Y
        X, y = df.iloc[:, 2:], df.iloc[:, 1]
        if X.shape[1] > 0 and X.shape[0] > 0:
            A = [.5, 1, 2.5, 5, 7.5, 10, 15, 20, 25, 30, 35, 40, 50, 100, 200, 250, 300, 350, 400, 450, 500, 750, 1000, 10000]
            reg = linear_model.LassoCV(cv=5, random_state=33, alphas=A).fit(X, y)
            score = reg.score(X,y)
            print(score)
            print(reg.coef_)
            print(reg.intercept_)
            print(reg.alpha_)
        
        
        
    print('\n')
    # take the coefficients and put them with the title of the column so we see how they correspond
    
    # name the dictionary after the gage
    
    # keys are the columns names
    
    # coef_ are the values



10140700
(3336, 11)
0.947161487080195
[0.01357412 0.01747925 0.         0.         0.         1.01470776
 0.02561295 0.03343919]
6.878046857676097
200.0


10149000
(8065, 11)
0.11954387079851214
[ 0.00683248 -0.          0.01598802]
28.85774016463674
100.0
0.7649713294420044
[ 0.         -0.         -0.          0.          0.03263075  0.
 -0.          0.00201287  0.03752761]
21.713721653997986
50.0


10155200
(7204, 11)
0.4864231211621002
[-0.         -0.          0.16659429 -0.          0.08532963  0.24694304
  0.0652233 ]
111.04790153203282
1000.0
0.4620337762936083
[ 0.15979677 -0.          0.         -0.          0.14118899 -0.
  0.05598438  0.25829747  0.07787862]
109.00011904084818
1000.0


09064600
(11541, 12)
0.815607925512552
[-0.10177725  0.16972244  0.78158122  0.24131747]
26.34945216640051
0.5


09081000
(8480, 12)
0.9855018836294911
[ 0.06576309 -0.17842695 -0.11801097 -0.17834858  0.56426032]
-39.88310302231707
200.0


09073300
(15208, 12)
0.9656501983764276
[-0.10091295

C:\Users\sjrek\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:476: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 17927.797946927254, tolerance: 1271.8991081345212
  positive)


09033300
(5034, 12)
0.9101064704856108
[0.03083769 0.17184461 1.62456556 0.48430597]
-5.4129922793418075
100.0


09359010
(10433, 12)
0.9252832140151238
[-0.         -0.          0.43358034  0.         -0.        ]
3.573997169594037
350.0


09358000
(10464, 12)
0.957424849019943
[-0.0100687  -0.42123888  0.53923195  0.1576872  -0.03293394]
8.154808575360008
1.0


09359020
(10834, 12)
0.9523449076252403
[-0.08293142 -0.45945802  1.15856994  0.247041   -0.09014809]
25.297667727987715
0.5


09359500
(8929, 12)
0.9574124091758875
[0.13785343 1.5660001  0.31765586]
2.265563212731081
250.0


09146020
(7361, 12)
0.9434545748629733
[ 0.0263607   0.52720193  0.20100936 -0.18099336 -0.00755804]
9.721819775923379
0.5


09112200
(14121, 12)
0.9916420911697041
[ 1.13770392 -0.07570682 -0.08932575  0.12046346]
8.892346174212264
0.5


09037500
(39320, 12)


09413500
(13118, 11)
0.8851967936123424
[0.74094762]
11.086114643956932
1000.0


09060799
(1122, 12)
0.7857862093840612
[ 0.51118532  0.68545732 

C:\Users\sjrek\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:472: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 40323.74566922337, tolerance: 14843.069612826292
  tol, rng, random, positive)
C:\Users\sjrek\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:472: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 26884.27788645914, tolerance: 14843.069612826292
  tol, rng, random, positive)
C:\Users\sjrek\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:472: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 53547.626539615914, tolerance: 14843.069612826292
  tol, rng, random, positive)
C:\Users\sjrek\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:472: ConvergenceWarning: Objective did not converge. You 

This is awesome! Now, we need to save this info somehow. I think a dictionary will work fine.

In [92]:
X

Empty DataFrame
Columns: [09057500, 09034250, 09019500, 09034500, 09065100, 09034000, 09066325, 09041400, 09038500, 09021000]
Index: []

In [93]:
y

Series([], Name: 09037500, dtype: object)

In [90]:
y

Series([], Name: 09037500, dtype: object)

In [78]:
SKU

NameError: name 'SKU' is not defined

In [41]:
df

datetime 10140700 10126000 10092700 10105900 10168000 10109000  \
0     2012-04-11     35.7     1680      765      123     12.9      217   
1     2012-04-12     48.9     1680      814      179     38.0      248   
2     2012-04-13     57.5     1730      854      174     18.5      239   
3     2012-04-14     44.5     1830      766      159     28.2      222   
4     2012-04-15     46.5     1960      763      142     16.3      208   
...          ...      ...      ...      ...      ...      ...      ...   
3331  2021-05-25      100      369      652     27.8     48.1      204   
3332  2021-05-26      117      423      666     31.0     50.7      188   
3333  2021-05-27      109      338      616     29.1     70.6      186   
3334  2021-05-28      107      287      536     29.8     97.4      188   
3335  2021-05-29     95.7      313      515     21.4      123      194   

     10140100 10136500 10141000  
0        12.5      289      299  
1        26.9      403      520  
2        25.3      381      450  
3        21.6      297      221  
4        18.5      256      180  
...       ...      ...      ...  
3331     64.2      244     93.0  
3332     86.0      224     75.4  
3333     77.7      228     82.5  
3334     73.6      220     74.6  
3335     61.1      235     96.5  

[3336 rows x 10 columns]

In [16]:
# instead of using the regular Cross Validation, try this:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html

In [ ]:
    # define grid
    grid = dict()
    grid['alpha'] = np.arange(0.1, 1, 0.01)
    # define search
    search = GridSearchCV(model, grid, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
    # search for the best model
    results = search.fit(X, y)
    # print results of the best model
    print('MAE: %.3f' % results.best_score_)
    print('Config: %s' % results.best_params_)

In [23]:
    # define the Lasso Model
    model = Lasso(alpha=0.1)
    # define the model evaluation method
    cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=33)
    # evaluate model
    scores = cross_val_score(model, X, y, scoring='neg_mean_absolute_error', cv=cv)
    # force scores to be positive
    scores = np.absolute(scores)
    print('Mean MAE: %.3f (%.3f)' % (mean(scores), std(scores)))

10126000 10092700 10171000 10105900 10168000 10109000 10140100 10136500  \
0        1680      765      187      123     12.9      217     12.5      289   
1        1680      814      192      179     38.0      248     26.9      403   
2        1730      854      179      174     18.5      239     25.3      381   
3        1830      766      169      159     28.2      222     21.6      297   
4        1960      763      169      142     16.3      208     18.5      256   
...       ...      ...      ...      ...      ...      ...      ...      ...   
3331      369      652      123     27.8     48.1      204     64.2      244   
3332      423      666      117     31.0     50.7      188     86.0      224   
3333      338      616      121     29.1     70.6      186     77.7      228   
3334      287      536      125     29.8     97.4      188     73.6      220   
3335      313      515      128     21.4      123      194     61.1      235   

     10141000  
0         299  
1         520  
2         450  
3         221  
4         180  
...       ...  
3331     93.0  
3332     75.4  
3333     82.5  
3334     74.6  
3335     96.5  

[3336 rows x 9 columns]

In [24]:
y

0       35.7
1       48.9
2       57.5
3       44.5
4       46.5
        ... 
3331     100
3332     117
3333     109
3334     107
3335    95.7
Name: 10140700, Length: 3336, dtype: object

In [38]:
df

datetime 09076300 09067020 09112500 09078600 09080400 09114500  \
0     2018-07-01      272      255      139      NaN      164      395   
1     2018-07-02      259      243      130      NaN      198      375   
2     2018-07-03      247      227      126      NaN      208      357   
3     2018-07-04      250      219      125      NaN      207      356   
4     2018-07-05      244      208      118      NaN      207      343   
...          ...      ...      ...      ...      ...      ...      ...   
1059  2021-05-25      395      885      553      NaN      120      818   
1060  2021-05-26      439      927      628      NaN      120      920   
1061  2021-05-27      406      855      544      NaN      119      864   
1062  2021-05-28      496      950      649      NaN      114      959   
1063  2021-05-29      574      962      709      NaN      110     1050   

     09113980 09059500 09073400 09110000 09119000  
0        29.7     34.8     63.3      303     19.9  
1        25.1     32.5     61.3      298     21.4  
2        22.7     30.6     62.4      294     22.2  
3        22.5     29.2     72.9      298     20.5  
4        22.0     26.8     72.5      296     18.1  
...       ...      ...      ...      ...      ...  
1059     36.2      210      168      336      120  
1060     35.1      221      178      371      124  
1061     34.8      198      161      380      138  
1062     28.5      228      187      391      151  
1063     23.8      220      202      401      173  

[1064 rows x 12 columns]

## YES! This is what I was looking for! Now, I need to start building the Lasso Regression models for use in production.